'use strict';
const $=id=>document.getElementById(id);let current=null;
const invalidate=()=>{current=null;$('results').hidden=true;$('message').textContent='';};
['csv','inventory','project'].forEach(id=>$(id).addEventListener('input',invalidate));
$('example').onclick=()=>{invalidate();$('project').value='Sample website migration';$('csv').value='source,target,status\n/old-guide,/guide,301\n/guide,/learn/guide,301\n/loop-a,/loop-b,301\n/loop-b,/loop-a,301\n/contact,/contact,301\n/sale,/offers,302\n/about,/company,301\n/about,/team,301';$('inventory').value='/old-guide\n/guide\n/loop-a\n/loop-b\n/contact\n/sale\n/about\n/forgotten-page';};
$('clear').onclick=()=>{invalidate();['csv','inventory','project'].forEach(id=>$(id).value='');};
let fileVersion=0;$('file').onchange=async()=>{const version=++fileVersion;invalidate();const f=$('file').files[0];if(!f)return;if(f.size>1000000){$('message').textContent='File exceeds the 1 MB limit.';return;}try{const text=await f.text();if(version!==fileVersion)return;$('csv').value=text;$('message').textContent='CSV loaded. Run the review to check it.';}catch{$('message').textContent='Could not read this file. Try pasting the CSV.';}};
$('analyze').onclick=()=>{invalidate();try{current=MoveLedger.audit($('csv').value,$('inventory').value,100);$('results').hidden=false;$('stats').innerHTML=[['Rules reviewed',current.rules],['Error findings',current.errors],['Review findings',current.warnings]].map(([k,v])=>`<div class="stat"><strong>${v}</strong><span>${k}</span></div>`).join('');$('findings').innerHTML=current.findings.length?current.findings.map(f=>`<tr><td><span class="sev ${f.severity}">${MoveLedger.esc(f.severity)}</span></td><td>${MoveLedger.esc(f.check)}</td><td>${MoveLedger.esc(f.source)}</td><td>${MoveLedger.esc(f.detail)}</td></tr>`).join(''):'<tr><td colspan="4">No issues found by supported checks. Live-site verification is still required.</td></tr>';$('message').textContent='Review complete. Findings are counts of issues, not unique affected URLs.';}catch(e){$('message').textContent=e.message;}};
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export').onclick=()=>{if(current)download(MoveLedger.findingsCSV(current),'moveledger-findings.csv','text/csv;charset=utf-8');};
$('report').onclick=()=>{if(current)download(MoveLedger.report(current,$('project').value),'moveledger-review.html','text/html;charset=utf-8');};
