(function(root){'use strict';
function parseCSV(text){
 text=String(text).replace(/^\uFEFF/,'');if(text.length>1000000)throw Error('File is larger than 1 MB.');
 const rows=[];let row=[],field='',quoted=false,closed=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){field+='"';i++;}else{quoted=false;closed=true;}}else field+=c;continue;}
 if(c==='"'){if(field||closed)throw Error('Malformed CSV quote. Quote the whole field.');quoted=true;}
 else if(c===','){row.push(field);field='';closed=false;}
 else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field='';closed=false;}
 else {if(closed&&c.trim())throw Error('Unexpected text after a quoted field.');if(!closed)field+=c;}}
 if(quoted)throw Error('Unclosed CSV quote.');row.push(field);if(row.some(v=>v.trim()))rows.push(row);return rows;
}
function key(value){const v=String(value||'').trim();if(!v||/[\s\\*^$(){}[\]|#]/.test(v)||/%(?![a-f0-9]{2})/i.test(v))return null;
 if(v.startsWith('/')&&!v.startsWith('//')){try{const u=new URL(v,'https://local.invalid');if(u.pathname+u.search!==v)return null;return v;}catch{return null;}}
 try{const u=new URL(v);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.hash)return null;return u.href;}catch{return null;}}
function audit(text,inventory='',limit=100,destinations=''){
 const rows=parseCSV(text);if(rows.length<2)throw Error('Add a header and at least one redirect rule.');const headers=rows.shift().map(v=>v.trim().toLowerCase());
 const find=names=>headers.findIndex(v=>names.includes(v));const si=find(['source','from','source_path','redirect from']),ti=find(['target','to','destination','destination_path','redirect to']),ci=find(['status','status_code']);
 if(si<0||ti<0)throw Error('Use source,target headers (or Redirect from,Redirect to).');if(new Set(headers).size!==headers.length)throw Error('CSV headers must be unique.');if(rows.length>limit)throw Error(`This edition supports ${limit.toLocaleString()} rules. Your file has ${rows.length.toLocaleString()}.`);
 const findings=[],map=new Map(),valid=[];const add=(severity,check,source,detail,row='')=>findings.push({severity,check,source,detail,row});
 rows.forEach((r,i)=>{const n=i+2;if(r.length!==headers.length){add('error','Column count',r[si]||'',`Row ${n} has ${r.length} fields; expected ${headers.length}.`,n);return;}const s=key(r[si]),t=key(r[ti]);if(!s||!t){add('error','Unsupported URL',r[si],`Row ${n}: use exact absolute paths or HTTP(S) URLs without fragments, whitespace, wildcards or regex.`,n);return;}
 const code=ci>=0?r[ci].trim():'301';if(!['301','302','303','307','308'].includes(code))add('error','Invalid status',s,`Row ${n}: unsupported or missing redirect status "${code}".`,n);else if(!['301','308'].includes(code))add('warning','Temporary redirect',s,`Status ${code}: confirm whether a permanent redirect is intended.`,n);
 valid.push({source:s,target:t,row:n,status:code});if(!map.has(s))map.set(s,new Set());map.get(s).add(t);if(s===t)add('error','Self redirect',s,'Source and destination are the same.',n);
 });
 const counts=new Map();valid.forEach(r=>counts.set(r.source,(counts.get(r.source)||0)+1));for(const [s,targets] of map){if(targets.size>1)add('error','Conflicting destinations',s,`Multiple destinations: ${[...targets].join(' | ')}. Choose the intended rule.`);else if(counts.get(s)>1)add('warning','Duplicate source',s,`${counts.get(s)} identical source rows. Remove redundant rules.`);}
 for(const [s,targets] of map){if(targets.size!==1||targets.has(s))continue;const seen=new Set([s]),path=[s];let current=s,reason='';while(map.has(current)){const nexts=map.get(current);if(nexts.size!==1){reason='ambiguous';break;}const next=[...nexts][0];path.push(next);if(seen.has(next)){reason='loop';break;}seen.add(next);current=next;}
 const preview=path.length>12?[...path.slice(0,6),'…',...path.slice(-3)]:path;
 if(reason==='loop')add('error','Redirect loop',s,preview.join(' → '));else if(reason==='ambiguous')add('error','Ambiguous chain',s,`Chain reaches conflicting rules: ${preview.join(' → ')}`);else if(path.length>2)add('warning','Redirect chain',s,`${path.length-1} hops: ${preview.join(' → ')}`);
 }
 const readList=(value,label)=>{if(value.length>1000000)throw Error(`${label} is larger than 1 MB.`);const entries=value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(entries.length>limit*2)throw Error(`${label} supports up to ${limit*2} entries.`);return new Set(entries.map(v=>{const k=key(v);if(!k)add('error',`Invalid ${label} entry`,v,'Use one exact path or full HTTP(S) URL per line, without a header.');return k;}).filter(Boolean));};
 const old=readList(inventory,'inventory');for(const s of old)if(!map.has(s))add('warning','Unmapped inventory URL',s,'No source rule found. Record whether this URL stays unchanged, needs a redirect, or is intentionally retired.');
 const dest=readList(destinations,'destination inventory');if(dest.size)for(const r of valid)if(!map.has(r.target)&&!dest.has(r.target))add('warning','Destination not in inventory',r.source,`${r.target} is absent from your supplied destination inventory. Verify it exists and is appropriate.`,r.row);
 return {rules:rows.length,validRules:valid.length,inventory:old.size,destinations:dest.size,findings,errors:findings.filter(f=>f.severity==='error').length,warnings:findings.filter(f=>f.severity==='warning').length};
}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function cell(v){let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function findingsCSV(result){return '\uFEFF'+[['severity','check','source','detail','row'],...result.findings.map(f=>[f.severity,f.check,f.source,f.detail,f.row])].map(r=>r.map(cell).join(',')).join('\r\n');}
function report(result,project){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(project||'Migration review')}</title><style>body{font:15px/1.6 Arial;color:#17312e;max-width:1000px;margin:40px auto;padding:20px}h1{font-size:36px}table{width:100%;border-collapse:collapse;font-size:12px}td,th{padding:12px;border:1px solid #ddd;text-align:left;overflow-wrap:anywhere}aside{padding:16px;background:#eef2e8}footer{margin-top:35px;color:#555}@media print{body{margin:0}tr{break-inside:avoid}}</style></head><body><p>MOVELEDGER / MIGRATION REVIEW</p><h1>${esc(project||'Website migration review')}</h1><p>Generated ${esc(new Date().toISOString())}. Review status: awaiting human review.</p><aside>${result.rules} rules • ${result.inventory} old inventory URLs • ${result.destinations} destination inventory URLs • ${result.errors} error findings • ${result.warnings} review findings</aside><h2>Scope</h2><p>Structural analysis of supplied exact-match rules only. No live URL requests or deployment verification. Origins, query strings, case and trailing slashes remain distinct. Findings are not a launch approval or an assurance about rankings.</p><h2>Findings</h2><table><thead><tr><th>Severity</th><th>Check</th><th>Source</th><th>Review</th></tr></thead><tbody>${result.findings.length?result.findings.map(f=>`<tr><td>${esc(f.severity)}</td><td>${esc(f.check)}</td><td>${esc(f.source)}</td><td>${esc(f.detail)}</td></tr>`).join(''):'<tr><td colspan="4">No issues found by the supported checks. Complete live-site verification before launch.</td></tr>'}</tbody></table><h2>Human review record</h2><p>Reviewer: __________________ Date: __________________</p><p>Open exceptions and reasons: ____________________________________</p><p>Live HTTP checks completed: ____ Content relevance checked: ____ Rollback owner confirmed: ____</p><p>Launch decision (record separately): ______________________________</p><footer>MoveLedger v1 • Keep this report with the reviewed CSV and release record. A downloaded report can be edited; it is not a signed attestation.</footer></body></html>`;}
 const api={parseCSV,key,audit,esc,findingsCSV,report};if(typeof module!=='undefined')module.exports=api;else root.MoveLedger=api;
})(typeof globalThis!=='undefined'?globalThis:this);
